version: '3.8'

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - signal-data:/var/lib/signal-cli
      - data:/app/data

volumes:
  data:
  signal-data: